### ISSUE TITLE
 'mavicpro_sp_2.0_battmod__dji_system.bin' it's not downloaded！How to do？

### ISSUE THREAD

**Issue by yh6895** [brett8883/DJI_Super-Patcher#52] opened 2019-11-05 16:17 UTC
I can't find 'mavicpro_sp_2.0_battmod__dji_system.bin'   Because it's not downloaded！How to do？Thank !

**Comment by brett8883** [comment] 2019-11-06 06:32
Strange I’ll look at it but it’s here https://github.com/brett8883/Super-Firmware_Cache/raw/2.0/MavicPro/FC_bin/MavicPro_SP_2.0_BattMod_03.02.44.12_dji_system.bin

**Comment by yh6895** [comment] 2019-11-06 06:53
Thank you very much for your reply！But I can't see it。Take a look at my screenshot  There's not even a raw folder。

**Comment by yh6895** [comment] 2019-11-07 18:05
I found it. Thank you very much!

**Comment by brett8883** [comment] 2019-11-09 06:01
> I found it. Thank you very much!

Glad you found it. The link above is the dissect link so clicking it will start the download process without further interaction. By default this means the file will end up in your downloads folder unless you’ve changed the location of where your files get downloaded to

**Comment by brett8883** [comment] 2019-11-11 03:24
I just tried it and it automatically downloaded for me so I am not sure what happened in your case. Maybe GitHub was down at that moment in time?

**Comment by yh6895** [comment] 2019-11-11 19:18
I don't know! I guess it's my network problem here. I download the file on your website and put it into the corresponding path to run.Fortunately, it worked.

**Comment by brett8883** [comment] 2019-11-15 14:16
Very good. I’m gonna close this issue since you got it to work and as far as I can tell it’s working as intended now. Open a new issue if anybody else has the same problem

**Closed by brett8883** 2019-11-15 14:16 UTC
